version: '3'
services:
  db:
    container_name: be-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '27012001'
    ports:
      - '3307:3307'
    volumes:
      - mysql:/data/mysql
    env_file:
      - .env

volumes:
  mysql:
    driver: local
  redis:
    driver: local
